---
title: "Appendix 1: Full Forecast Partition"
csl: ecology.csl
output:
  pdf_document:
    keep_tex: no
  html_document: default
geometry: left=1in, right=1in, top=1in, bottom=1in, headheight=12pt, letterpaper
header-includes:
- \usepackage[textsize=tiny,textwidth=2.1cm]{todonotes}
- \usepackage{mathptmx}
- \usepackage{upgreek}
- \usepackage{bm}
- \usepackage{setspace}
- \usepackage{booktabs}
- \usepackage{floatrow}
- \newcounter{box}
- \newcommand{\boxnumber}{\addtocounter{box}{1} \thebox \thinspace}
- \floatstyle{boxed}
- \newfloat{Box}{tbph}{box}
- \floatsetup[table]{capposition=top}
fontsize: 11pt
bibliography: /Users/atredenn/Dropbox/Bibliography/ecocast.bib
---

\newcommand{\smalltodo}[2][]
    {\todo[caption={#2}, #1]
    {\begin{spacing}{0.5}#2\end{spacing}}}
\setlength{\abovedisplayskip}{0pt}

Forecast variance is equal to

\begin{equation}
\begin{aligned}[b]
V_{T+q}^{(F)} = \ &V_{T+q}^{(I)} + V_{T+q}^{(PA)} + V_{T+q}^{(D)} + V_{T+q}^{(PS)} \\
&+ \epsilon_{T+q}^{(I,PA)} + \epsilon_{T+q}^{(I,D)} + \epsilon_{T+q}^{(I,PS)} + \epsilon_{T+q}^{(PA,PS)} + \epsilon_{T+q}^{(PA,D)} + \epsilon_{T+q}^{(D,PS)} \\
&+ \epsilon_{T+q}^{(I,PA,D)} + \epsilon_{T+q}^{(I,PA,PS)} + \epsilon_{T+q}^{(I,D,PS)} + \epsilon_{T+q}^{(PA,D,PS)} \\
&+ \epsilon_{T+q}^{(I,PA,D,PS)},
\end{aligned}
\end{equation}

\noindent{}with interaction terms calculated as

\begin{align}
\epsilon^{(I,PA)}_{T+q} &= V^{(I+PA)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(PA)}_{T+q}\right] \\
\epsilon^{(I,D)}_{T+q} &= V^{(I+D)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(D)}_{T+q}\right] \\
\epsilon^{(I,PS)}_{T+q} &= V^{(I+PS)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(PS)}_{T+q}\right] \\
\epsilon^{(PA,D)}_{T+q} &= V^{(PA+D)}_{T+q} - \left[V^{(PA)}_{T+q} + V^{(D)}_{T+q}\right] \\
\epsilon^{(PA,PS)}_{T+q} &= V^{(PA+PS)}_{T+q} - \left[V^{(PA)}_{T+q} + V^{(PS)}_{T+q}\right] \\
\epsilon^{(D,PS)}_{T+q} &= V^{(D+PS)}_{T+q} - \left[V^{(D)}_{T+q} + V^{(PS)}_{T+q}\right] \\
\epsilon^{(I,PA,D)}_{T+q} &= V^{(I+PA+PD)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(PA)}_{T+q} + V^{(D)}_{T+q}\right] - \left[\epsilon^{(I,PA)}_{T+q} + \epsilon^{(I,D)}_{T+q} + \epsilon^{(PA,D)}_{T+q} \right] \\
\epsilon^{(I,PA,PS)}_{T+q} &= V^{(I+PA+PS)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(PA)}_{T+q} + V^{(PS)}_{T+q}\right] - \left[\epsilon^{(I,PA)}_{T+q} + \epsilon^{(I,PS)}_{T+q} + \epsilon^{(PA,PS)}_{T+q} \right] \\
\epsilon^{(I,D,PS)}_{T+q} &= V^{(I+D+PS)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(D)}_{T+q} + V^{(PS)}_{T+q}\right] - \left[\epsilon^{(I,D)}_{T+q} + \epsilon^{(I,PS)}_{T+q} + \epsilon^{(D,PS)}_{T+q} \right] \\
\epsilon^{(PA,D,PS)}_{T+q} &= V^{(PA+D+PS)}_{T+q} - \left[V^{(PA)}_{T+q} + V^{(D)}_{T+q} + V^{(PS)}_{T+q}\right] - \left[\epsilon^{(PA,D)}_{T+q} + \epsilon^{(PA,PS)}_{T+q} + \epsilon^{(D,PS)}_{T+q} \right]
\end{align}
\begin{equation}
\begin{aligned}[b]
\epsilon^{(I,PA,D,PS)}_{T+q} &= V^{(F)}_{T+q} - \left[V^{(I)}_{T+q} + V^{(PA)}_{T+q} + V^{(D)}_{T+q} + V^{(PS)}_{T+q}\right] \\ &- \left[\epsilon^{(I,PA)}_{T+q} + \epsilon^{(I,D)}_{T+q} + \epsilon^{(I,PS)}_{T+q} + \epsilon^{(PA,D)}_{T+q} + \epsilon^{(PA,PS)}_{T+q} + \epsilon^{(D,PS)}_{T+q} \right] \\ 
&- \left[\epsilon^{(I,PA,D)}_{T+q} + \epsilon^{(I,PA,PS)}_{T+q} + \epsilon^{(I,D,PS)}_{T+q} + \epsilon^{(PA,D,PS)}_{T+q} \right]
\end{aligned}
\end{equation}

\noindent{}which simplifies to

\begin{align}
\textbf{Two-way interactions:} \quad \gamma^{(i,j)} &= V^{(i+j)} - \sum_{m = (i,j)}V^{(m)} \\
\textbf{Three-way interactions:} \quad \epsilon^{(i,j,k)} &= V^{(i+j+k)} - \sum \bm{\gamma} - \sum_{m = (i,j,k)}V^{(m)} \\
\textbf{Four-way interactions:} \quad \Delta^{(i,j,k,l)} &= V^{(i+j+k+l)} - \sum \bm{\epsilon} - \sum \bm{\gamma} - \sum_{m = (i,j,k,l)}V^{(m)} \\
\end{align}